spring.application.name=MyMusic
spring.datasource.url=jdbc:postgresql://localhost/MyMusic
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
audiodb.url=https://www.theaudiodb.com/api/v1/json/123/